### ISSUE TITLE
觀影心得回饋

### ISSUE THREAD

**Issue by azole** [nanachi10101000/hello-git#1]
謝謝你的影片心得，我非常喜歡你的結論喔，你說得對，不要侷限自己，試著多給自己一些可能性，大部分的人都不是真的不行，而是在不行之前先放棄了，當然，我們不是無所不能，不過，要我說，當一個 100 分的工程師...至少我自己不是啦，但要當一個持續成長、懂得學習改進、一直進步的工程師，這個我相信我們大部分的人都是做得到的。

至於過去，既然都叫過去的，就讓它過去吧，未來永遠是比較重要的，而現在可以決定未來，所以沒有什麼比好好把握現在更重要的事了～

**Comment by nanachi10101000** [comment]
謝謝老師鼓勵，縱使過去不順遂，也要記取教訓，開創更好的未來。
